<script>
    import { onMount } from "svelte";
    import {
        FileText,
        GitBranch,
        Eye,
        CheckCircle,
        XCircle,
        Clock,
        List,
        Zap,
        Users,
        ArrowRight,
        BarChart2,
    } from "lucide-svelte";

    // Simple components for the documentation
    const Section = {
        title: "",
        content: "",
    };
</script>

<div
    class="min-h-screen bg-slate-950 text-slate-200 font-sans selection:bg-indigo-500/30 p-8 md:p-16"
>
    <div class="max-w-5xl mx-auto space-y-12">
        <!-- Header -->
        <header class="border-b border-white/10 pb-8">
            <h1
                class="text-4xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400 mb-4"
            >
                Arquitectura & Flujos de VoteTok
            </h1>
            <p class="text-xl text-slate-400">
                Documentación técnica detallada de la lógica de encuestas,
                estados y visualización.
            </p>
            <div class="mt-4 flex gap-4 text-sm font-mono text-slate-500">
                <span>v1.0.0</span>
                <span>•</span>
                <span>Generated by Antigravity</span>
                <span>•</span>
                <span>{new Date().toLocaleDateString()}</span>
            </div>
        </header>

        <!-- 1. Core Concept -->
        <section>
            <h2
                class="text-2xl font-bold text-white mb-6 flex items-center gap-2"
            >
                <Zap class="text-yellow-400" /> Core Concept
            </h2>
            <div
                class="prose prose-invert max-w-none text-slate-300 bg-white/5 p-6 rounded-2xl border border-white/5"
            >
                <p>
                    La aplicación se basa en un <strong
                        >Sistema de Feed de Votación Híbrido</strong
                    >
                    que alterna entre dos modos de visualización principales:
                    <span class="text-white font-bold bg-white/10 px-1 rounded"
                        >Feed (Scroll Vertical Clásico)</span
                    >
                    y
                    <span class="text-white font-bold bg-white/10 px-1 rounded"
                        >Reels (Pantalla Completa Inmersiva)</span
                    >.
                </p>
                <p class="mt-4">
                    Cada unidad de contenido es un <code>Post</code> que contiene
                    una encuesta de tipo variable. El estado visual de cada post
                    depende críticamente de dos vectores:
                </p>
                <ul class="list-disc pl-5 mt-2 space-y-2">
                    <li>
                        <strong>Estado del Usuario:</strong> ¿Ha votado ya? (HasVoted)
                    </li>
                    <li>
                        <strong>Estado del Tiempo:</strong> ¿Ha expirado la encuesta?
                        (IsClosed)
                    </li>
                </ul>
            </div>
        </section>

        <!-- 2. Poll Types Logic -->
        <section>
            <h2
                class="text-2xl font-bold text-white mb-6 flex items-center gap-2"
            >
                <GitBranch class="text-indigo-400" /> Tipos de Encuesta y Lógica
            </h2>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Standard -->
                <div
                    class="bg-slate-900/50 p-6 rounded-xl border border-white/10 hover:border-indigo-500/50 transition-colors"
                >
                    <div class="flex items-center gap-2 mb-4">
                        <div
                            class="p-2 bg-indigo-500/20 rounded-lg text-indigo-400"
                        >
                            <FileText size={20} />
                        </div>
                        <h3 class="text-xl font-bold text-white">
                            Standard Poll
                        </h3>
                    </div>
                    <div class="space-y-4 text-sm text-slate-400">
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Flujo No Votado:</strong
                            >
                            Muestra opciones con botones de "Votar". No muestra porcentajes.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Flujo Votado / Cerrado:</strong
                            >
                            Sustituye botones por barras de progreso, porcentajes
                            y avatares de amigos. Resalta la opción elegida.
                        </div>
                        <div
                            class="mt-4 p-3 bg-black/30 rounded border border-white/5 font-mono text-xs"
                        >
                            <div class="flex flex-col gap-1 text-slate-400">
                                <div>
                                    <span class="text-indigo-400">if</span>
                                    (hasVoted || isClosed)
                                    <span class="text-emerald-400">-></span> Show
                                    Percentages
                                </div>
                                <div>
                                    <span class="text-indigo-400">else</span>
                                    <span class="text-emerald-400">-></span> Show
                                    Vote Buttons
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Quiz -->
                <div
                    class="bg-slate-900/50 p-6 rounded-xl border border-white/10 hover:border-yellow-500/50 transition-colors"
                >
                    <div class="flex items-center gap-2 mb-4">
                        <div
                            class="p-2 bg-yellow-500/20 rounded-lg text-yellow-400"
                        >
                            <CheckCircle size={20} />
                        </div>
                        <h3 class="text-xl font-bold text-white">
                            Quiz (Trivial)
                        </h3>
                    </div>
                    <div class="space-y-4 text-sm text-slate-400">
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Lógica Específica:</strong
                            >
                            Tiene una <code>correctOptionId</code>. El usuario
                            solo tiene un intento.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Feedback Visual:</strong
                            >
                            <ul>
                                <li class="flex items-center gap-2 mt-1">
                                    <span
                                        class="w-2 h-2 rounded-full bg-emerald-500"
                                    ></span> Acierto: Verde + Glow
                                </li>
                                <li class="flex items-center gap-2 mt-1">
                                    <span
                                        class="w-2 h-2 rounded-full bg-red-500"
                                    ></span> Fallo: Rojo (Muestra la correcta en
                                    verde)
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- Tierlist -->
                <div
                    class="bg-slate-900/50 p-6 rounded-xl border border-white/10 hover:border-purple-500/50 transition-colors"
                >
                    <div class="flex items-center gap-2 mb-4">
                        <div
                            class="p-2 bg-purple-500/20 rounded-lg text-purple-400"
                        >
                            <List size={20} />
                        </div>
                        <h3 class="text-xl font-bold text-white">
                            Tierlist (Ranking)
                        </h3>
                    </div>
                    <div class="space-y-4 text-sm text-slate-400">
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Fase de Draft (Local):</strong
                            >
                            El usuario hace clic en opciones para construir su ranking
                            1, 2, 3... Las opciones seleccionadas obtienen un badge
                            temporal <code>#1</code>.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Completado:</strong
                            >
                            Al rankear todas las opciones, el post se considera "Respondido"
                            localmente, pero no enviado hasta confirmar o implícito.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Visualización Resultados:</strong
                            >
                            El orden visual de las opciones cambia físicamente en
                            el DOM para reflejar el ranking global promedio una vez
                            votado.
                        </div>
                    </div>
                </div>

                <!-- Swipe -->
                <div
                    class="bg-slate-900/50 p-6 rounded-xl border border-white/10 hover:border-red-500/50 transition-colors"
                >
                    <div class="flex items-center gap-2 mb-4">
                        <div class="p-2 bg-red-500/20 rounded-lg text-red-500">
                            <ArrowRight size={20} />
                        </div>
                        <h3 class="text-xl font-bold text-white">
                            Swipe Style
                        </h3>
                    </div>
                    <div class="space-y-4 text-sm text-slate-400">
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Modo Interactivo:</strong
                            >
                            Pila de cartas. Interacción Tinder (Derecha=Like, Izquierda=Dislike).
                            Cada swipe es un voto individual.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Transición a Resultados:</strong
                            >
                            Solo tras completar todos los swipes (o si la encuesta
                            cierra), la vista se transforma dramáticamente en un
                            <strong>Grid de Resultados</strong> estático.
                        </div>
                    </div>
                </div>

                <!-- Collab -->
                <div
                    class="bg-slate-900/50 p-6 rounded-xl border border-white/10 hover:border-emerald-500/50 transition-colors md:col-span-2"
                >
                    <div class="flex items-center gap-2 mb-4">
                        <div
                            class="p-2 bg-emerald-500/20 rounded-lg text-emerald-500"
                        >
                            <Users size={20} />
                        </div>
                        <h3 class="text-xl font-bold text-white">
                            Collab (Abierta)
                        </h3>
                    </div>
                    <div
                        class="space-y-4 text-sm text-slate-400 grid grid-cols-1 md:grid-cols-2 gap-4"
                    >
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >Dinámica:</strong
                            >
                            Cualquier usuario puede añadir una opción nueva.
                        </div>
                        <div>
                            <strong class="text-slate-200 block mb-1"
                                >UI de Edición:</strong
                            >
                            Al pulsar "Añadir", aparece una tarjeta temporal de edición
                            de texto.
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- 3. State & Visualization Matrix -->
        <section>
            <h2
                class="text-2xl font-bold text-white mb-6 flex items-center gap-2"
            >
                <Eye class="text-cyan-400" /> Matriz de Estados de Visualización
            </h2>

            <div
                class="overflow-hidden rounded-xl border border-white/10 bg-slate-900/30"
            >
                <table class="w-full text-left text-sm text-slate-400">
                    <thead
                        class="bg-white/5 text-slate-200 uppercase font-bold text-xs"
                    >
                        <tr>
                            <th class="p-4">Contexto</th>
                            <th class="p-4">Estado: Abierta + No Votado</th>
                            <th class="p-4 text-indigo-300"
                                >Estado: Votado (Cualquier tiempo)</th
                            >
                            <th class="p-4 text-orange-300"
                                >Estado: Cerrada + No Votado</th
                            >
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-white/5">
                        <tr>
                            <td class="p-4 font-bold text-white">Acción Clic</td
                            >
                            <td class="p-4"
                                ><span class="text-green-400"
                                    >Registra Voto</span
                                ></td
                            >
                            <td class="p-4">Expande Info (No Vota)</td>
                            <td class="p-4 text-red-400"
                                >Solo Expande (Bloqueado)</td
                            >
                        </tr>
                        <tr>
                            <td class="p-4 font-bold text-white">Porcentajes</td
                            >
                            <td class="p-4">Ocultos</td>
                            <td class="p-4">Visibles (Animados)</td>
                            <td class="p-4">Visibles (Estáticos)</td>
                        </tr>
                        <tr>
                            <td class="p-4 font-bold text-white"
                                >Barras Progreso</td
                            >
                            <td class="p-4">Ocultas</td>
                            <td class="p-4">Visibles</td>
                            <td class="p-4"
                                >Visibles (Color atenuado si perdida)</td
                            >
                        </tr>
                        <tr>
                            <td class="p-4 font-bold text-white"
                                >Badges Selección</td
                            >
                            <td class="p-4">Ninguno</td>
                            <td class="p-4">Check / Borde Color</td>
                            <td class="p-4">Ninguno (Usuario no participó)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>

        <!-- 4. Detailed Component Flow -->
        <section>
            <h2 class="text-2xl font-bold text-white mb-6">
                Arbol de Componentes Críticos
            </h2>
            <div class="relative pl-8 border-l-2 border-white/10 space-y-8">
                <!-- PostCard -->
                <div class="relative">
                    <div
                        class="absolute -left-10 top-0 w-4 h-4 rounded-full bg-indigo-500 ring-4 ring-slate-950"
                    ></div>
                    <h3 class="text-xl font-bold text-white mb-2">
                        PostCard.svelte
                    </h3>
                    <p class="text-slate-400 mb-4">
                        Orquestador principal. Gestiona el estado local de UI.
                    </p>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div
                            class="bg-black/40 p-4 rounded border border-white/5"
                        >
                            <h4 class="font-bold text-indigo-400 mb-2">
                                Derived State Logic
                            </h4>
                            <pre
                                class="text-xs font-mono text-slate-300 overflow-x-auto">
const isClosed = endsAt &lt; Now;
const hasVoted = userVotes[id];
const shouldShowResults = hasVoted || isClosed;
const displayOptions = tierlist ? sorted : original;
                </pre>
                        </div>
                        <div
                            class="bg-black/40 p-4 rounded border border-white/5"
                        >
                            <h4 class="font-bold text-indigo-400 mb-2">
                                Event Handlers
                            </h4>
                            <ul
                                class="list-disc pl-4 text-xs text-slate-300 space-y-1"
                            >
                                <li>
                                    <code>handleOptionVote</code>: Gatekeeper.
                                    Checks <code>isClosed</code> before dispatching.
                                </li>
                                <li>
                                    <code>switchToReels</code>: Manages ViewMode
                                    transitions explicitly.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- OptionCard -->
                <div class="relative">
                    <div
                        class="absolute -left-10 top-0 w-4 h-4 rounded-full bg-cyan-500 ring-4 ring-slate-950"
                    ></div>
                    <h3 class="text-xl font-bold text-white mb-2">
                        OptionCard.svelte
                    </h3>
                    <p class="text-slate-400 mb-4">
                        Unidad atómica de visualización. Stateles (mostly).
                    </p>
                    <ul
                        class="bg-white/5 p-4 rounded-lg space-y-2 text-sm text-slate-300"
                    >
                        <li>
                            <strong>Props Critical:</strong>
                            <code>hasVoted</code>
                            (Boolean that triggers result view),
                            <code>isSelected</code>,
                            <code>isCorrectOption</code>.
                        </li>
                        <li>
                            <strong>Dynamic Styling:</strong> Calcula gradientes
                            HSL o Tailwind classes on the fly.
                        </li>
                        <li>
                            <strong>Animations:</strong> Las barras de progreso
                            tienen <code>transition-all duration-1000</code> para
                            efecto dramático al revelar.
                        </li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- 5. Análisis Profundo: Gaps, Bugs & Roadmap Creativo -->
        <section>
            <h2
                class="text-2xl font-bold text-white mb-6 flex items-center gap-2"
            >
                <BarChart2 class="text-rose-500" /> Falta por Implementar (Deep Dive
                & Creative)
            </h2>

            <div class="space-y-8">
                <!-- CRITICAL INTERACTION BUGS -->
                <div
                    class="bg-red-900/10 border border-red-500/30 p-6 rounded-2xl relative overflow-hidden"
                >
                    <div class="absolute top-0 right-0 p-4 opacity-5">
                        <XCircle class="w-24 h-24 text-red-500" />
                    </div>
                    <h3
                        class="text-xl font-bold text-red-400 mb-4 flex items-center gap-2 relative z-10"
                    >
                        <XCircle size={18} /> Interacciones Rotas (Prioridad Alta)
                    </h3>
                    <div
                        class="grid grid-cols-1 md:grid-cols-2 gap-4 relative z-10"
                    >
                        <div
                            class="p-3 bg-black/40 rounded border border-red-500/20"
                        >
                            <strong class="text-red-200 block text-sm mb-1"
                                >Avatar Click (Feed)</strong
                            >
                            <p class="text-xs text-red-300/70">
                                Al hacer clic en el avatar del autor en <code
                                    >PostCard</code
                                >, no ocurre nada.
                                <br /><span class="text-white">Fix:</span> Debe
                                abrir <code>UserProfileModal</code> con el ID del
                                autor.
                            </p>
                        </div>
                        <div
                            class="p-3 bg-black/40 rounded border border-red-500/20"
                        >
                            <strong class="text-red-200 block text-sm mb-1"
                                >Botón 'Seguir' (Feed)</strong
                            >
                            <p class="text-xs text-red-300/70">
                                El botón pequeño al lado del nombre en el feed
                                es puramente visual.
                                <br /><span class="text-white">Fix:</span>
                                Conectar a endpoint
                                <code>/api/users/:id/follow</code> y actualizar estado
                                reactivo.
                            </p>
                        </div>
                    </div>
                </div>

                <!-- FEED ACTIONS ANALYSIS -->
                <div
                    class="bg-slate-900/40 p-6 rounded-2xl border border-white/5"
                >
                    <h3
                        class="text-xl font-bold text-slate-200 mb-4 flex items-center gap-2"
                    >
                        <ArrowRight class="text-indigo-400" size={18} /> Acciones
                        del Feed & Engagement
                    </h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <!-- Compartir -->
                        <div
                            class="p-4 bg-black/20 rounded-xl border border-white/5"
                        >
                            <div class="flex justify-between items-start mb-2">
                                <span
                                    class="text-white font-bold flex items-center gap-2"
                                    ><ArrowRight size={14} /> Compartir</span
                                >
                                <span
                                    class="bg-red-500/20 text-red-400 text-[10px] px-2 py-0.5 rounded uppercase font-bold"
                                    >Sin Lógica</span
                                >
                            </div>
                            <div class="text-xs text-slate-400 leading-relaxed">
                                <p>
                                    <strong>Estado Actual:</strong> Botón visualmente
                                    presente pero sin handler.
                                </p>
                                <p class="mt-2">
                                    <strong
                                        >Estándar Esperado (Instagram):</strong
                                    >
                                </p>
                                <ul class="list-disc pl-4 mt-1 space-y-1">
                                    <li>Native Share Sheet (Mobile).</li>
                                    <li>
                                        Deep Links (<code>/poll/[id]</code>).
                                    </li>
                                    <li>
                                        Generación de imágenes para IG Stories.
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <!-- Bookmarks -->
                        <div
                            class="p-4 bg-black/20 rounded-xl border border-white/5"
                        >
                            <div class="flex justify-between items-start mb-2">
                                <span
                                    class="text-white font-bold flex items-center gap-2"
                                    ><List size={14} /> Guardados</span
                                >
                                <span
                                    class="bg-red-500/20 text-red-400 text-[10px] px-2 py-0.5 rounded uppercase font-bold"
                                    >Sin Lógica</span
                                >
                            </div>
                            <div class="text-xs text-slate-400 leading-relaxed">
                                <p>
                                    <strong>Estado Actual:</strong> Icono inerte.
                                </p>
                                <p class="mt-2"><strong>Roadmap:</strong></p>
                                <ul class="list-disc pl-4 mt-1 space-y-1">
                                    <li>Tabla <code>UserBookmarks</code>.</li>
                                    <li>
                                        Colecciones privadas (ej. "Ideas",
                                        "Memes").
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- PROFILE EXPERIENCE -->
                <div
                    class="bg-slate-900/40 p-6 rounded-2xl border border-white/5"
                >
                    <h3
                        class="text-xl font-bold text-slate-200 mb-4 flex items-center gap-2"
                    >
                        <Users class="text-cyan-400" size={18} /> Experiencia de
                        Perfil (Faltantes)
                    </h3>

                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div
                            class="p-3 bg-black/30 rounded border border-white/5"
                        >
                            <strong class="text-white text-sm block mb-1"
                                >Vista de Grid vs Reels</strong
                            >
                            <p class="text-xs text-slate-400">
                                Actualmente el perfil es una lista plana. Falta
                                la vista de "Reels" (Grid de 3 columnas) típica
                                de TikTok/IG para consumo rápido.
                            </p>
                        </div>
                        <div
                            class="p-3 bg-black/30 rounded border border-white/5"
                        >
                            <strong class="text-white text-sm block mb-1"
                                >Edición de Perfil</strong
                            >
                            <p class="text-xs text-slate-400">
                                No hay botón para editar Bio, Avatar o Banner.
                                El usuario está atrapado con lo que tenga.
                            </p>
                        </div>
                        <div
                            class="p-3 bg-black/30 rounded border border-white/5"
                        >
                            <strong class="text-white text-sm block mb-1"
                                >Social Links</strong
                            >
                            <p class="text-xs text-slate-400">
                                Falta sección de enlaces externos (Linktree,
                                Instagram, Twitter) en la biografía.
                            </p>
                        </div>
                    </div>
                </div>

                <!-- CREATIVE & NEXT-GEN FEATURES -->
                <div
                    class="bg-gradient-to-br from-indigo-900/20 to-purple-900/20 p-6 rounded-2xl border border-indigo-500/30"
                >
                    <h3
                        class="text-xl font-bold text-white mb-4 flex items-center gap-2"
                    >
                        <Zap class="text-yellow-400" size={18} /> Roadmap Creativo
                        (The "Wow" Factor)
                    </h3>

                    <div class="space-y-4">
                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors rounded-lg"
                        >
                            <div
                                class="w-10 h-10 rounded-full bg-pink-500/20 flex items-center justify-center text-pink-400 shrink-0"
                            >
                                <Zap size={20} />
                            </div>
                            <div>
                                <h4 class="font-bold text-slate-200 text-sm">
                                    Integración de Música (Audio Polls)
                                </h4>
                                <p class="text-xs text-slate-400 mt-1">
                                    Permitir adjuntar un snippet de 30s de audio
                                    (Spotify/Preview) a la encuesta.
                                    <em
                                        >Ejemplo: "¿Cuál es el mejor drop?"
                                        vinculando dos audios.</em
                                    >
                                </p>
                            </div>
                        </div>

                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors rounded-lg"
                        >
                            <div
                                class="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 shrink-0"
                            >
                                <Eye size={20} />
                            </div>
                            <div>
                                <h4 class="font-bold text-slate-200 text-sm">
                                    Video Backgrounds (TikTok Style)
                                </h4>
                                <p class="text-xs text-slate-400 mt-1">
                                    Sustituir el fondo estático por videos en
                                    bucle (Autoplay, Muted). Haría la app
                                    infinitamente más dinámica.
                                </p>
                            </div>
                        </div>

                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors rounded-lg"
                        >
                            <div
                                class="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400 shrink-0"
                            >
                                <BarChart2 size={20} />
                            </div>
                            <div>
                                <h4 class="font-bold text-slate-200 text-sm">
                                    Creator Analytics
                                </h4>
                                <p class="text-xs text-slate-400 mt-1">
                                    Dashboard privado para el creador: "¿Qué
                                    demografía votó más?", "Horas pico de
                                    votación", "Tasa de retención".
                                </p>
                            </div>
                        </div>

                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0 hover:bg-white/5 transition-colors rounded-lg"
                        >
                            <div
                                class="w-10 h-10 rounded-full bg-orange-500/20 flex items-center justify-center text-orange-400 shrink-0"
                            >
                                <Users size={20} />
                            </div>
                            <div>
                                <h4 class="font-bold text-slate-200 text-sm">
                                    Modo "Battle" (Pantalla Dividida)
                                </h4>
                                <p class="text-xs text-slate-400 mt-1">
                                    Dos usuarios colaboran en vivo. La pantalla
                                    se divide en dos. Cada uno defiende una
                                    opción con video/audio en tiempo real.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- CREATION MANAGEMENT -->
                <div
                    class="bg-slate-900/40 p-6 rounded-2xl border border-white/5 opacity-75"
                >
                    <h3
                        class="text-lg font-bold text-slate-400 mb-4 flex items-center gap-2"
                    >
                        <ArrowRight class="text-slate-500" size={18} /> Gestión Básica
                        (Maintenance)
                    </h3>
                    <div class="space-y-4">
                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0"
                        >
                            <div class="w-32 font-bold text-slate-300 text-sm">
                                Gestor Borradores
                            </div>
                            <div class="flex-1">
                                <span
                                    class="text-xs bg-emerald-500/20 text-emerald-300 px-1 rounded mr-2"
                                    >IMPLEMENTED</span
                                >
                                <span class="text-xs text-slate-400"
                                    >Guarda estado local, recupera al abrir
                                    modal. Robusto.</span
                                >
                            </div>
                        </div>
                        <div
                            class="flex gap-4 p-3 border-b border-white/5 last:border-0"
                        >
                            <div class="w-32 font-bold text-slate-300 text-sm">
                                Edición
                            </div>
                            <div class="flex-1">
                                <span
                                    class="text-xs bg-red-500/20 text-red-300 px-1 rounded mr-2"
                                    >MISSING</span
                                >
                                <span class="text-xs text-slate-400"
                                    >Falta edición post-publicación y borrado de
                                    encuestas propias.</span
                                >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- 6. Critical Flows Diagram -->
        <section>
            <h2
                class="text-2xl font-bold text-white mb-6 flex items-center gap-2"
            >
                <ArrowRight class="text-pink-400" /> Flujos de Aplicación
            </h2>

            <div class="space-y-8">
                <!-- Creation Flow -->
                <div
                    class="p-6 rounded-2xl border border-white/10 bg-slate-900/50"
                >
                    <h3 class="text-lg font-bold text-white mb-6">
                        1. Flujo de Creación (The Builder Pattern)
                    </h3>
                    <div
                        class="flex flex-col md:flex-row items-center gap-4 text-xs font-mono text-slate-300"
                    >
                        <div
                            class="bg-black/40 p-3 rounded border border-white/10 w-full md:w-auto text-center"
                        >
                            <span class="text-indigo-400 block mb-1"
                                >Trigger</span
                            >
                            Create Modal
                        </div>
                        <ArrowRight class="hidden md:block text-slate-600" />
                        <div class="block md:hidden text-slate-600">↓</div>

                        <div
                            class="bg-black/40 p-3 rounded border border-white/10 w-full md:w-auto text-center border-emerald-500/30"
                        >
                            <span class="text-emerald-400 block mb-1"
                                >Checks</span
                            >
                            Load Drafts?
                        </div>
                        <ArrowRight class="hidden md:block text-slate-600" />
                        <div class="block md:hidden text-slate-600">↓</div>

                        <div
                            class="bg-black/40 p-3 rounded border border-white/10 w-full md:w-32 text-center text-clip overflow-hidden"
                        >
                            <span class="text-blue-400 block mb-1">Config</span>
                            Type + Options
                            <br /><span class="opacity-50">(Reactive)</span>
                        </div>
                        <ArrowRight class="hidden md:block text-slate-600" />
                        <div class="block md:hidden text-slate-600">↓</div>

                        <div
                            class="bg-black/40 p-3 rounded border border-white/10 w-full md:w-auto text-center"
                        >
                            <span class="text-orange-400 block mb-1">Meta</span>
                            Duration + Collab
                        </div>
                        <ArrowRight class="hidden md:block text-slate-600" />
                        <div class="block md:hidden text-slate-600">↓</div>

                        <div
                            class="bg-indigo-600/20 p-3 rounded border border-indigo-500/50 w-full md:w-auto text-center shadow-[0_0_15px_rgba(99,102,241,0.2)]"
                        >
                            <span class="text-white font-bold block mb-1"
                                >SUBMIT</span
                            >
                            POST /api/polls
                        </div>
                    </div>
                </div>

                <!-- Interaction Flow -->
                <div
                    class="p-6 rounded-2xl border border-white/10 bg-slate-900/50"
                >
                    <h3 class="text-lg font-bold text-white mb-6">
                        2. Flujo de Interacción: Tierlist (The Optimistic UI)
                    </h3>
                    <div class="flex flex-col gap-4">
                        <div class="flex items-start gap-4">
                            <div
                                class="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center border border-white/10 shrink-0"
                            >
                                1
                            </div>
                            <div>
                                <h4 class="text-white font-bold text-sm">
                                    User Click
                                </h4>
                                <p class="text-slate-400 text-xs mt-1">
                                    El usuario hace click en una opción en el
                                    feed.
                                </p>
                            </div>
                        </div>

                        <div class="w-0.5 h-6 bg-white/10 ml-4"></div>

                        <div class="flex items-start gap-4">
                            <div
                                class="w-8 h-8 rounded-full bg-yellow-500/20 text-yellow-500 flex items-center justify-center border border-yellow-500/30 shrink-0"
                            >
                                2
                            </div>
                            <div>
                                <h4 class="text-white font-bold text-sm">
                                    Local Mutable State
                                </h4>
                                <p class="text-slate-400 text-xs mt-1">
                                    <code>rankingDrafts[postId]</code> se actualiza
                                    instantáneamente. Se añade el ID al array. El
                                    badge se renderiza inmediatamente.
                                </p>
                            </div>
                        </div>

                        <div class="w-0.5 h-6 bg-white/10 ml-4"></div>

                        <div class="flex items-start gap-4">
                            <div
                                class="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center border border-white/10 shrink-0"
                            >
                                3
                            </div>
                            <div>
                                <h4 class="text-white font-bold text-sm">
                                    Completion Check
                                </h4>
                                <p class="text-slate-400 text-xs mt-1">
                                    Reactive statement: <code
                                        >rankingDraft.length === options.length</code
                                    >. Si es true, el estado visual cambia a
                                    "Completed".
                                </p>
                            </div>
                        </div>

                        <div class="w-0.5 h-6 bg-white/10 ml-4"></div>

                        <div class="flex items-start gap-4">
                            <div
                                class="w-8 h-8 rounded-full bg-indigo-500/20 text-indigo-400 flex items-center justify-center border border-indigo-500/30 shrink-0"
                            >
                                4
                            </div>
                            <div>
                                <h4 class="text-white font-bold text-sm">
                                    Async Submission
                                </h4>
                                <p class="text-slate-400 text-xs mt-1">
                                    El envío real del voto ocurre o bien al
                                    completar o mediante acción explícita
                                    (dependiendo de la implementación final en <code
                                        >onVote</code
                                    >).
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer
            class="mt-20 border-t border-white/10 pt-8 text-center text-slate-600 text-sm"
        >
            VoteTok Internal Documentation - Restricted Access
        </footer>
    </div>
</div>

<style>
    :global(body) {
        background-color: #020617;
    }
</style>
